### PR TITLE
fixing conditionals for plan

### PR DESCRIPTION
**Pull request by ian-hoyle**

### CODE REVIEW

**Comment by ian-hoyle** [comment]
Terraform plan does not allow the use of attributes for ecr and zip in lambda resource.
I have changed the conditionals to allow plan to work 
In the existing code there was
`aws_lambda_function.lambda_function.*.arn[0]` I would have expected to use `aws_lambda_function.lambda_function[0].arn`
which is best
Instead of the conditionals I could create a new lambda_ecr module but this would be a lot of duplicated code - which way do you want

**Comment by MancunianSam** [comment]
This looks sensible but you've got a lot of duplication checking for the function_name and arn. You can assign them to local variables and reference those. There's a temp branch https://github.com/nationalarchives/da-terraform-modules/compare/fix-optional-lambda...temp-branch-for-changes?expand=1 with this on.

**Comment by ian-hoyle** [comment]
that looks better

**Comment by ian-hoyle** [comment]
@MancunianSam can you review again

**Review by MancunianSam — APPROVED** [review]
:+1:

**Pull request merged**
